### ISSUE TITLE
Error: Timed out while waiting for handshake

### ISSUE THREAD

**Issue by Jack89ita** [tgxhx/webpack-ftp-upload-plugin#1]
Hi, when i use your plugin i get the following error:
Error: Timed out while waiting for handshake
Any clue?
Thank you very much

**Comment by tgxhx** [comment]
Hello, you can make sure ftp upload function is normal in the following way.
1. Please make sure you have the correct username and password.
2. Please ensure that your account has the write permission of the remote path.
3. You can try to connect to the server using the FTP tool and write the file in the remote path.

**Comment by basz** [comment]
is this package using scp? so not a real FTP?

**Comment by tgxhx** [comment]
@basz No, I use the package [scp2](https://www.npmjs.com/package/scp2).

**Comment by basz** [comment]
I saw, so it uses the ssh as a protocol, not ftp.

**Comment by Jack89ita** [comment]
Ok guys thank you for clarify this. I needed FTP protocol, so this is usless for me.

**Comment by basz** [comment]
me too. its name is a little misleading :-)

https://www.npmjs.com/package/deploy-kit worked for me
